
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 8;
  public static final int RGB = 2;
  public static final int EOF = 0;
  public static final int JV = 7;
  public static final int error = 1;
  public static final int VIR = 4;
  public static final int RPAREN = 5;
  public static final int HEX = 9;
  public static final int PVIR = 6;
  public static final int LPAREN = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RGB",
  "LPAREN",
  "VIR",
  "RPAREN",
  "PVIR",
  "JV",
  "NUM",
  "HEX"
  };
}

