
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int NUM = 7;
  public static final int COMMA = 5;
  public static final int RGB = 2;
  public static final int RPAREN = 4;
  public static final int error = 1;
  public static final int SEMI = 6;
  public static final int LPAREN = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RGB",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "SEMI",
  "NUM"
  };
}

